.TH ABRAFLEXI-RAIFFEISENBANK-EVENTS 1 "October 2023" "1.0" "User Commands"
.SH NAME
abraflexi-raiffeisenbank-events \- Import PDF statements to events in AbraFlexi
.SH SYNOPSIS
.B abraflexi-raiffeisenbank-events
.SH DESCRIPTION
This command downloads Raiffeisenbank PDF statements and imports them to events in the AbraFlexi application.
.SH OPTIONS
None.
.SH AUTHOR
Written by Vitex.