.TH ABRAFLEXI-RAIFFEISENBANK-SETUP 1 "October 2023" "1.0" "User Commands"
.SH NAME
abraflexi-raiffeisenbank-setup \- Setup AbraFlexi Raiffeisenbank integration
.SH SYNOPSIS
.B abraflexi-raiffeisenbank-setup
.SH DESCRIPTION
This command sets up the AbraFlexi Raiffeisenbank integration by configuring necessary parameters and settings.
.SH OPTIONS
None.
.SH AUTHOR
Written by Vitex.