.TH ABRAFLEXI-RAIFFEISENBANK-TRANSACTIONS 1 "October 2023" "1.0" "User Commands"
.SH NAME
abraflexi-raiffeisenbank-transactions \- Handle Raiffeisenbank transactions in AbraFlexi
.SH SYNOPSIS
.B abraflexi-raiffeisenbank-transactions
.SH DESCRIPTION
This command handles Raiffeisenbank transactions within the AbraFlexi application, including importing and processing transactions.
.SH OPTIONS
None.
.SH AUTHOR
Written by Vitex.