.TH ABRAFLEXI-RAIFFEISENBANK-STATEMENTS 1 "October 2023" "1.0" "User Commands"
.SH NAME
abraflexi-raiffeisenbank-statements \- Manage Raiffeisenbank statements in AbraFlexi
.SH SYNOPSIS
.B abraflexi-raiffeisenbank-statements
.SH DESCRIPTION
This command manages Raiffeisenbank statements within the AbraFlexi application, including downloading and processing statements.
.SH OPTIONS
None.
.SH AUTHOR
Written by Vitex.